Scarcity Manifested ERC721 upgraded
degen-vc/scarcity pull request #5
Opened 2021-09-14 14:16 UTC by eirlis

2021-09-14 15:29 UTC, ytumanov requested changes

2021-09-14 15:29 UTC, ytumanov commented on contracts/core/rarity.sol
> +library Address {
can be imported from openzeppelin

2021-09-14 15:29 UTC, ytumanov commented on contracts/core/rarity.sol
> +abstract contract ERC165 is IERC165 {
can be imported from openzeppelin and other contracts

2021-09-14 15:29 UTC, ytumanov commented on contracts/core/rarity.sol
> +    // string constant public name = "Scarcity Manifested";
remove?

2021-09-14 15:29 UTC, ytumanov commented on contracts/core/rarity.sol
>          require(_isApprovedOrOwner(msg.sender, _summoner));
_msgSender()

2021-09-19 04:52 UTC, hayalet27 approved these changes

2021-09-19 14:40 UTC, hayalet27 approved these changes

2021-09-19 14:41 UTC, hayalet27 requested changes
Kontrol edilsin

2021-09-20 10:36 UTC, ytumanov approved these changes

2021-09-20 10:36 UTC, merged